{% set name = "pytest-xvfb" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4ba642de05499940db7f65ee111621939be513e3e75c3da9156b7235e2ed8cf

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - pytest >=2.8.1
    - python >=3.5
    - pyvirtualdisplay >=1.3
    - setuptools

test:
  imports:
    - pytest_xvfb
  commands:
    # skip this command in OS-X: https://github.com/conda-forge/pytest-xvfb-feedstock/issues/3
    - pytest --help  # [not osx]

about:
  home: https://github.com/The-Compiler/pytest-xvfb
  license: MIT
  license_family: MIT
  # license file included in the recipe for now:
  # https://github.com/The-Compiler/pytest-xvfb/pull/26
  license_file: LICENSE
  summary: A pytest plugin to run Xvfb for tests.

extra:
  recipe-maintainers:
    - nicoddemus
