{% set name = "pytest-xvfb" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 90593634427d974b272e845793e4533f5b827c9d84c051879013624504175e44

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2
  run:
    - pytest >=2.8.1
    - python >={{ python_min }}
    - pyvirtualdisplay >=1.3
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_xvfb
  commands:
    # skip this command in OS-X: https://github.com/conda-forge/pytest-xvfb-feedstock/issues/3
    - pytest --help  # [not osx]

about:
  home: https://github.com/The-Compiler/pytest-xvfb
  license: MIT
  license_family: MIT
  # license file included in the recipe for now:
  # https://github.com/The-Compiler/pytest-xvfb/pull/26
  license_file: LICENSE
  summary: A pytest plugin to run Xvfb for tests.

extra:
  recipe-maintainers:
    - nicoddemus
