appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uROCFhoTo7+Q89zc0lHv9TBp4J0dnzT2MSeacc8LNgVANZlUC4EWYEpBjU170gxELI40o2E3K2d9fuZXyoOiUEAIVWstnvZw0VklsL9WasgaYE8xI31qt8c/2GPiaDHJ7Z07aWhaqQDMOFp3RMZWmQEU4u6CE2SgVFRMFI8gWBVdgXbtAalFvymX9bpsQbe7SHXQgXUKtUIVXbZJZcKiJdIGZNuvWsmz/kWrDbiEZhN4v8WcGr5QYhwe8NIWYuw5RWv76qgiet5gyyGVw0QdXrf1x6D+WoOqAvoFgB6g18gryWJF/xAd8q5bHsZsZNuWi2rUiXQs9M2F1CBz20EjFEqaQqcCCiISYxcLHwWIDkUyyjKPB7GXqw9xINsgcAuu1rzxucB8Z6+WmM9xCFnoqi0y23mdo4LU+kK2ngKxUkwz7yiGCMc2HAYxyR9JnjsEd0WbiH4tlLEgVQ7QDaMJUA5p9zdTMxqupsUTem2qU+4aInnSFoUXtz+Lqi4cwVwlVsBdTJ+ZVLqVgcRtDdVsFs6voutKvtfZCx4RN7S6RfSWlKKk+OpgBI84iOXr1nefU7BYdT4eOj5XziIcRyHzdXfiszIEXiSPN6XGSqbpW8wTbnWeauaOuhe82Cg/ubK9x6lBmezeL/DmHj6IQn/kheoKqAn+hOHWH+GEQk9O1Ik=}
conda_forge_output_validation: true
